midiIn: "USB MIDI Interface"

outputs:
  osc:
    ip: 127.0.0.1
    port: 8765
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: false 
  keyboard-commands: true
  audio-files: true

# LEGEND
#  5 - Small Allison
#  7 - Christian
#  8 - Joan
#  9 - John
# 10 - Allison
# 11 - Matt
# 12 - Patrick
# 13 - Helen
# 14 - Susan 1
# 15 - Susan 2
# 16 - Medium Allison

midi-cue-mapping:
  - light: 1
    housescene: "full"
  # Opening
  - light: 3
    mute: [21, 22]
    unmute: [14, 20, 23, 24]
    fader: [23, 24]
    value: [80, 80]
  - light: 4
    mute: [14]
  # A
  - light: 5
    unmute: [5, 12]
  - light: 10
    unmute: [10]
  - light: 15
    unmute: [13]
  - light: 16
    mute: [5, 10, 12]
  - light: 17
    unmute: [5, 7, 9, 10]
  - light: 18
    unmute: [12]
  - light: 19
    unmute: [11]
  - light: 20
    mute: [5, 7, 9, 11, 12, 13]
    unmute: [10]
  # B
  - light: 25
    mute: [10]
    unmute: [16]
    houselights: [10]
    rgbws: [[100, 100, 100, 100]]
    transitions: [10]
    effects: ["None"]
  - light: 26
    unmute: [12]
    houselights: [10]
    rgbws: [[0, 0, 0, 0]]
    transitions: [10]
    effects: ["Light Board Control"]
  - light: 27
    mute: [12]
    unmute: [10]
  # C
  - light: 30
    mute: [10, 16]
    unmute: [11, 12]
    houselights: [9]
    rgbws: [[0, 0, 0, 0]]
    transitions: [3]
    effects: ["Custom Rainbow"]
  - light: 31
    unmute: [5, 7, 9]
    mute: [11]
  - light: 32
    mute: [12]
  - light: 33
    unmute: [12]
  - light: 34
    mute: [7, 9]
    unmute: [10]
  # D
  - light: 35
    mute: [5, 12]
    unmute: [8, 10, 16]
  # E
  - light: 40
    mute: [8, 16, 10]
    unmute: [5, 7, 9, 12, 13]
  - light: 41
    unmute: [11]
  - light: 42
    mute: [11]
  # F
  - light: 43
    mute: [7, 9]
    unmute: [10, 11]
  - light: 44
    mute: [5, 10]
  # G
  - light: 45
    mute: [11, 12, 13]
    unmute: [8, 16]
  - light: 46
    unmute: [10]
  - light: 47
    mute: [10]
  # H
  - light: 50
    mute: [8, 16]
    unmute: [12]
  # I
  - light: 51
    unmute: [5]
  - light: 54
    unmute: [16]
  - light: 55
    mute: [5]
  - light: 56
    mute: [12]
    unmute: [8]
  - light: 60
    mute: [8, 16]
    unmute: [10]
  - light: 65
    mute: [10]
    unmute: [16]
  # J
  - light: 75
    mute: [16]
    unmute: [10]
  - light: 80
    mute: [10]
    unmute: [5, 13]
  - light: 81
    unmute: [12]
    mute: [13]
  - light: 82
    unmute: [13]
  - light: 85
    mute: [5, 12, 13]
    unmute: [10]
  # K
  - light: 90
    mute: [10]
    unmute: [11, 12]
  - light: 91
    mute: [11, 12]
    unmute: [16]
  - light: 92
    fader: [23, 24]
    value: [90, 90]
  # L
  - light: 95
    mute: [16]
    # TELEVISION
    file: "C:\\Users\\LALT\\Documents\\Shows\\Funhome_SFX\\television-scene.mp3"
  - light: 99
    unmute: [5, 12]
  - light: 101
    unmute: [10]
  - light: 105
    mute: [12]
    unmute: [13]
  - light: 110
    mute: [5]
    unmute: [12]
  # M
  - light: 111
    unmute: [5, 7, 8, 9, 11, 14, 15, 16]
  - light: 121
    mute: [5, 7, 8, 9, 11, 13, 14, 15, 16]
  # N
  - light: 125
    mute: [12]
    fader: [23, 24]
    value: [127, 127]
  - light: 126
    # DOOR SFX
    file: "C:\\Users\\LALT\\Documents\\Shows\\Funhome_SFX\\door-slam-amp.mp3"
  - light: 130
    unmute: [5, 7, 9, 12]
    fader: [23, 24]
    value: [80, 80]
  - light: 131
    mute: [9]
  - light: 132
    mute: [7]
  - light: 135
    mute: [5, 12]
  # O
  - light: 140
    mute: [10]
    unmute: [8, 16]
  - light: 141
    unmute: [12]
  - light: 142
    mute: [12]
  # P
  - light: 145
    mute: [8, 16]
  - light: 146
    unmute: [5, 12]
  - light: 150
    mute: [12]
    unmute: [10]
  - light: 151
    mute: [10]
  # Q
  - light: 156
    mute: [5]
  - light: 157
    # PHONE SFX
    file: "C:\\Users\\LALT\\Documents\\Shows\\Funhome_SFX\\phone-ring-short.mp3"
  - light: 160
    unmute: [12, 16]
  - light: 161
    mute: [12]
    unmute: [13]
  - light: 165
    mute: [13]
    unmute: [8]
  - light: 170
    mute: [8, 16]
    unmute: [10]
  - light: 171
    unmute: [12, 13]
  # R
  - light: 180
    mute: [12, 13]
    unmute: [16, 8]
  - light: 181
    mute: [10]
  - light: 185
    unmute: [12, 13]
  - light: 186
    mute: [12]
  - light: 187
    mute: [8]
  - light: 190
    mute: [16]
  - light: 205
    mute: [13]
    unmute: [8, 12]
  - light: 206
    unmute: [10, 16]
  # S
  - light: 207
    mute: [8, 10]
  - light: 209
    mute: [16]
  - light: 210
    unmute: [10]
  # T
  - light: 220
    mute: [10]
  - light: 235
    mute: [12]
    unmute: [10]
  # U
  - light: 245
    unmute: [5]
  - light: 250
    unmute: [16]
  - light: 265
    mute: [5, 16]
  - light: 270
    mute: [10]
