midiIn: USB

outputs:
  osc:
    ip: 127.0.0.1
    port: 8765
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: true 

midi-cue-mapping:
  - light: 1
    sound: 1 
  - light: 3
    sound: 3 
  - light: 4
    sound: 4 
  - light: 14
    sound: 5  
  - light: 16
    sound: 6
  - light: 18
    sound: 7
  - light: 20
    sound: 8
  - light: 24
    sound: 10
  - light: 26
    sound: 11
  - light: 32
    sound: 15
  - light: 34
    sound: 16
  # - light: 38
  #   sound: 17
  - light: 38
    sound: 20
  - light: 42
    sound: 19
  - light: 44
    sound: 21
  - light: 46
    sound: 22
  - light: 48
    sound: 23
  - light: 50
    sound: 24
  - light: 54
    sound: 25
  - light: 56
    sound: 26
  - light: 58
    sound: 30
  # - light: 60
  #   sound: 31
  - light: 62
    sound: 35
  - light: 64
    sound: 37
  - light: 70
    sound: 39
  - light: 74
    sound: 40
  - light: 76
    sound: 41
  - light: 78
    sound: 42
  - light: 80
    sound: 43
  - light: 82
    sound: 44
  - light: 84
    sound: 45
  - light: 86
    sound: 46
  - light: 88
    sound: 47
  - light: 90
    sound: 48
  - light: 94
    sound: 49
  - light: 96
    sound: 50
  - light: 100
    sound: 51
  - light: 102
    sound: 52
  - light: 104
    sound: 53
  - light: 106
    sound: 54
  - light: 108
    sound: 55
  - light: 110
    sound: 56
  - light: 112
    sound: 57
  - light: 116
    sound: 58
  - light: 118
    sound: 59
  - light: 120
    sound: 60
  - light: 124
    sound: 61
  - light: 126
    sound: 62
  - light: 136
    sound: 63
  - light: 140
    sound: 64
  - light: 142
    sound: 65
  - light: 144
    sound: 66
  - light: 146
    sound: 67
  - light: 148
    sound: 68
  - light: 150
    sound: 69
  - light: 152
    sound: 70
  - light: 154
    sound: 71
  - light: 156
    sound: 72
  - light: 158
    sound: 73
  - light: 162
    sound: 74
  - light: 164
    sound: 75
  - light: 166
    sound: 76
  - light: 168
    sound: 77
  - light: 170
    sound: 78
  - light: 172
    sound: 79
  - light: 174
    sound: 80
  - light: 176
    sound: 81
  - light: 180
    sound: 82
  - light: 182
    sound: 83
  - light: 186
    sound: 84
  - light: 187
    sound: 9
  - light: 192
    sound: 12
  - light: 194
    sound: 14
  - light: 200
    sound: 85
  - light: 202
    sound: 86
  - light: 204
    sound: 87
  - light: 206
    sound: 88
  - light: 208
    sound: 89
  - light: 210
    sound: 90
  - light: 212
    sound: 91
  - light: 214
    sound: 92
  - light: 215
    sound: 93
  - light: 216
    sound: 94
  - light: 218
    sound: 95
  - light: 220
    sound: 96
  - light: 224
    sound: 97
  - light: 226
    sound: 98
  - light: 228
    sound: 99
  - light: 230
    sound: 2
  - light: 238
    sound: 13
