midiIn: "USB MIDI Interface"

outputs:
  osc:
    ip: 127.0.0.1
    port: 8765
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: false 
  keyboard-commands: true
  audio-files: true

# Love, Loss, and What I Wore Projector Cues + Song Cue

midi-cue-mapping:
  - light: 6
    keyboard: "L"
  - light: 15
    keyboard: "L"
  - light: 16
    keyboard: "L"
  - light: 18
    keyboard: "L"
  - light: 19
    keyboard: "L"
  - light: 20
    keyboard: "L"
  - light: 71
    keyboard: "L"
  - light: 72
    keyboard: "L"
  - light: 75
    keyboard: "L"
  - light: 121
    keyboard: "L"
  - light: 122
    keyboard: "L"
  - light: 162
    keyboard: "L"
  - light: 163
    keyboard: "L"
  - light: 164
    keyboard: "L"
  - light: 171
    keyboard: "L"
  - light: 172
    keyboard: "L"
  - light: 173
    keyboard: "L"
  - light: 265
    file: "C:\\Users\\LALT\\Documents\\Shows\\LoveLoss\\Cyndi Lauper - Girls Just Want To Have Fun (Official Video) [PIb6AZdTr-A].mp3"
