midiIn: "USB MIDI Interface"

outputs:
  osc:
    ip: 127.0.0.1
    port: 8765
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: false 
  keyboard-commands: true
  audio-files: true

# Beowulf and the Bard Cue Listings

midi-cue-mapping:
  # sound cues
  - light: 10 # set levels for transitions note that 100 = U
    unmute: [21, 22, 23, 24]
    fader: [23, 24]
    value: [85, 85]
  - light: 23
    keyboard: "A"
  - light: 25 
    keyboard: "B"
  - light: 40
    keyboard: "C"
  - light: 45
    keyboard: "D"
  - light: 50
    fader: [23, 24]
    value: [110, 110] # scale is 0-127, want this high for Josh
  # House Lights Josh Entrance
  # Note: midlights are 2, 3, 6, 7, 10, 11
  # Full house is 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  - light: 55
    houselights: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    rgbws: [[0, 0, 0, 0]]
    transitions: [0.9]
    effects: ["Custom Rainbow"]
    keyboard: "J"  # J for Josh
  # Kill house lights
  - light: 65
    houselights: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    rgbws: [[0, 0, 0, 0]]
    transitions: [3]
    effects: ["Light Board Control"]
  # And kill the Josh music
  - light: 67
    keyboard: "K"
  # transitions
  - light: 70
    keyboard: "E"
    fader: [23, 24]
    value: [85, 85] 
  - light: 80
    keyboard: "F"
  - light: 105
    keyboard: "G"
  - light: 110
    keyboard: "H"
  - light: 125
    keyboard: "M"
  - light: 130
    keyboard: "N"
  - light: 150
    keyboard: "O"
  - light: 155
    keyboard: "P"
  - light: 160
    keyboard: "Q"
    fader: [23, 24]
    value: [65, 65] 
  - light: 175
    keyboard: "R"