midiIn: "USB MIDI Interface"

outputs:
  osc:
    ip: 127.0.0.1
    port: 8765
  midi-pc:
    name: UM-ONE
    channel: 1
  qlab: false 
  keyboard-commands: true
  audio-files: true

midi-cue-mapping:
  - light: 1
    mute: 1
    fader: 1
    value: 0
  - light: 2
    unmute: 1
    fader: 1
    value: 100
  - light: 4
    mute: 1
    fader: 1
    value: 0
  # Rewind
  - light: 22
    keyboard: "B"
  # Rewind
  - light: 24
    keyboard: "B"
  # Tiptoe
  - light: 26
    keyboard: "A"
  # Stop tiptoe
  - light: 27
    keyboard: "S"
  # Tiptoe
  - light: 28
    keyboard: "A"
  # Stop tiptoe
  - light: 29
    keyboard: "S"
  # Tiptoe
  - light: 30
    keyboard: "A"
  # Stop tiptoe
  - light: 31
    keyboard: "S"
  # Horse
  - light: 40
    keyboard: "X"
